spring:
    application:
        name: talker
    config:
        import: classpath:/application-secret.yml
    
---
spring:
    config:
        activate:
            on-profile: development
       
    thymeleaf:
        cache: false
        
    datasource:
        driver-class-name: org.postgresql.Driver
        
    jpa:
        hibernate:
            ddl-auto: update
            
    
        
        
